const questions = [
  // -------------------- GNS 210 – Anatomy (40) --------------------
  { q: "Largest organ in the human body?", options: ["Heart", "Liver", "Skin", "Lung"], answer: 2, category: "GNS210" },
  { q: "How many chambers does the heart have?", options: ["2", "3", "4", "5"], answer: 2, category: "GNS210" },
  { q: "Functional unit of the kidney?", options: ["Neuron", "Nephron", "Alveoli", "Osteon"], answer: 1, category: "GNS210" },
  { q: "The femur is located in?", options: ["Arm", "Leg", "Head", "Chest"], answer: 1, category: "GNS210" },
  { q: "Which system includes skin, hair, nails?", options: ["Nervous", "Integumentary", "Skeletal", "Muscular"], answer: 1, category: "GNS210" },
  { q: "Red blood cells are produced in?", options: ["Spleen", "Bone Marrow", "Liver", "Kidney"], answer: 1, category: "GNS210" },
  { q: "Where are the alveoli found?", options: ["Kidney", "Lung", "Heart", "Liver"], answer: 1, category: "GNS210" },
  { q: "Which organ produces insulin?", options: ["Pancreas", "Liver", "Kidney", "Spleen"], answer: 0, category: "GNS210" },
  { q: "The diaphragm separates?", options: ["Heart and lungs", "Thoracic and abdominal cavities", "Kidneys and bladder", "Brain and spinal cord"], answer: 1, category: "GNS210" },
  { q: "Largest part of the brain?", options: ["Cerebellum", "Medulla", "Cerebrum", "Pons"], answer: 2, category: "GNS210" },
  { q: "The trachea is part of which system?", options: ["Digestive", "Respiratory", "Circulatory", "Nervous"], answer: 1, category: "GNS210" },
  { q: "Which structure connects muscles to bones?", options: ["Ligaments", "Tendons", "Cartilage", "Fascia"], answer: 1, category: "GNS210" },
  { q: "The skin is part of?", options: ["Muscular system", "Integumentary system", "Circulatory system", "Skeletal system"], answer: 1, category: "GNS210" },
  { q: "Which blood cells fight infection?", options: ["Red", "White", "Platelets", "Plasma"], answer: 1, category: "GNS210" },
  { q: "The spinal cord passes through?", options: ["Skull", "Vertebrae", "Rib cage", "Pelvis"], answer: 1, category: "GNS210" },
  { q: "Which organ detoxifies chemicals?", options: ["Kidney", "Liver", "Lung", "Spleen"], answer: 1, category: "GNS210" },
  { q: "Which type of joint is the shoulder?", options: ["Hinge", "Ball and Socket", "Pivot", "Gliding"], answer: 1, category: "GNS210" },
  { q: "The cerebellum controls?", options: ["Breathing", "Balance and coordination", "Heart rate", "Vision"], answer: 1, category: "GNS210" },
  { q: "Which organ stores red blood cells?", options: ["Liver", "Spleen", "Kidney", "Pancreas"], answer: 1, category: "GNS210" },
  { q: "The alveoli function in?", options: ["Gas exchange", "Blood filtration", "Hormone secretion", "Immune response"], answer: 0, category: "GNS210" },
  { q: "Which organ produces bile?", options: ["Liver", "Pancreas", "Stomach", "Gallbladder"], answer: 0, category: "GNS210" },
  { q: "The axial skeleton includes?", options: ["Limbs", "Skull and vertebrae", "Pelvis", "Shoulder girdle"], answer: 1, category: "GNS210" },
  { q: "Ligaments connect?", options: ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Bone to organ"], answer: 0, category: "GNS210" },
  { q: "Tendons connect?", options: ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Bone to organ"], answer: 1, category: "GNS210" },
  { q: "Which hormone regulates calcium in bones?", options: ["Insulin", "Parathyroid", "Adrenaline", "Thyroxine"], answer: 1, category: "GNS210" },
  { q: "The humerus is in?", options: ["Leg", "Arm", "Head", "Torso"], answer: 1, category: "GNS210" },
  { q: "Largest vein in the body?", options: ["Aorta", "Vena Cava", "Pulmonary vein", "Jugular vein"], answer: 1, category: "GNS210" },
  { q: "Smallest bones are found in?", options: ["Ear", "Hand", "Foot", "Skull"], answer: 0, category: "GNS210" },
  { q: "Which gland is the master gland?", options: ["Pituitary", "Thyroid", "Adrenal", "Pancreas"], answer: 0, category: "GNS210" },
  { q: "Which organ filters blood to produce urine?", options: ["Kidney", "Liver", "Heart", "Lung"], answer: 0, category: "GNS210" },
  { q: "What protects lungs from friction?", options: ["Pleura", "Pericardium", "Meninges", "Peritoneum"], answer: 0, category: "GNS210" },
  { q: "The cerebrum is responsible for?", options: ["Balance", "Thinking", "Breathing", "Heart rate"], answer: 1, category: "GNS210" },
  { q: "Which organ stores bile?", options: ["Liver", "Gallbladder", "Stomach", "Pancreas"], answer: 1, category: "GNS210" },
  { q: "Which organ is retroperitoneal?", options: ["Kidney", "Liver", "Heart", "Lung"], answer: 0, category: "GNS210" },
  { q: "Where is the thymus located?", options: ["Neck", "Between lungs", "Abdomen", "Pelvis"], answer: 1, category: "GNS210" },
  { q: "What is the functional unit of the respiratory system?", options: ["Alveoli", "Nephron", "Neuron", "Osteon"], answer: 0, category: "GNS210" },
  { q: "Which bone forms the forehead?", options: ["Frontal", "Parietal", "Occipital", "Temporal"], answer: 0, category: "GNS210" },
  { q: "Which bone forms the upper jaw?", options: ["Mandible", "Maxilla", "Zygomatic", "Nasal"], answer: 1, category: "GNS210" },
  { q: "The sternum protects?", options: ["Heart", "Lungs", "Both", "Brain"], answer: 2, category: "GNS210" },
  { q: "The patella is?", options: ["Knee cap", "Elbow bone", "Shoulder bone", "Ankle bone"], answer: 0, category: "GNS210" },
  { q: "The medulla oblongata controls?", options: ["Balance", "Heart rate", "Voluntary movement", "Vision"], answer: 1, category: "GNS210" },

  // -------------------- GNS 211 – Foundation (40) --------------------
  { q: "Which vital sign is considered the fifth vital sign?", options: ["Pain", "Pulse", "Respiration", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Normal adult blood pressure?", options: ["120/80 mmHg", "100/60 mmHg", "140/90 mmHg", "90/50 mmHg"], answer: 0, category: "GNS211" },
  { q: "Standard precautions prevent?", options: ["Patient comfort", "Infection spread", "Medication errors", "Diet errors"], answer: 1, category: "GNS211" },
  { q: "Hand hygiene reduces?", options: ["Pain", "Infection", "Stress", "Fatigue"], answer: 1, category: "GNS211" },
  { q: "Primary goal of nursing?", options: ["Diagnosis", "Patient care", "Research", "Administration"], answer: 1, category: "GNS211" },
  { q: "Which is a core nursing skill?", options: ["Suturing", "Medication administration", "Surgery", "Radiology"], answer: 1, category: "GNS211" },
  { q: "Normal adult pulse range?", options: ["40–60 bpm", "60–100 bpm", "100–120 bpm", "80–140 bpm"], answer: 1, category: "GNS211" },
  { q: "Fever is defined as?", options: [">37.5°C", ">38°C", ">39°C", ">36°C"], answer: 1, category: "GNS211" },
  { q: "Which oxygen saturation is normal?", options: ["<90%", "90–100%", "85–95%", "80–90%"], answer: 1, category: "GNS211" },
  { q: "Correct sequence of CPR?", options: ["CAB", "ABC", "BAC", "ACB"], answer: 0, category: "GNS211" },
  { q: "Normal adult respiration rate?", options: ["12–20/min", "20–30/min", "8–12/min", "10–18/min"], answer: 0, category: "GNS211" },
  { q: "Gloves are used for?", options: ["Protection", "Fashion", "Therapy", "Nutrition"], answer: 0, category: "GNS211" },
  { q: "Systolic pressure measures?", options: ["Heart relaxation", "Heart contraction", "Blood oxygen", "Pulse strength"], answer: 1, category: "GNS211" },
  { q: "Diastolic pressure measures?", options: ["Heart relaxation", "Heart contraction", "Pulse volume", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Which scale measures pain?", options: ["Glasgow", "Numeric", "APGAR", "Barthel"], answer: 1, category: "GNS211" },
  { q: "Which is part of patient safety?", options: ["Medication check", "Surgery alone", "Diagnosis only", "Lab work"], answer: 0, category: "GNS211" },
  { q: "Which is a nursing intervention?", options: ["Surgery", "Medication administration", "Diagnostic imaging", "Lab test"], answer: 1, category: "GNS211" },
  { q: "Standard precautions include?", options: ["Hand washing and PPE", "Diet planning", "Exercise", "Diagnostics"], answer: 0, category: "GNS211" },
  { q: "Which part of patient assessment?", options: ["Vital signs", "Lab result only", "Medication prescription", "Diet"], answer: 0, category: "GNS211" },
  { q: "Purpose of infection control?", options: ["Prevent spread", "Improve diet", "Administer drugs", "Surgery"], answer: 0, category: "GNS211" },
  { q: "Which part of hand hygiene is crucial?", options: ["Duration", "Brand", "Color", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Which is a core nursing responsibility?", options: ["Patient care", "Diagnosis", "Surgery", "Lab test"], answer: 0, category: "GNS211" },
  { q: "Which body system monitors infection?", options: ["Immune system", "Digestive system", "Skeletal system", "Muscular system"], answer: 0, category: "GNS211" },
  { q: "Normal body temperature?", options: ["36–37°C", "35–36°C", "37–38°C", "38–39°C"], answer: 0, category: "GNS211" },
  { q: "Which protects against pathogens?", options: ["Gloves", "Sterile equipment", "Masks", "All of the above"], answer: 3, category: "GNS211" },
  { q: "Purpose of vital signs?", options: ["Diagnose disease", "Assess physiological status", "Prescribe drugs", "Treat illness"], answer: 1, category: "GNS211" },
  { q: "Primary reason for patient assessment?", options: ["Medication", "Baseline health info", "Surgery", "Exercise plan"], answer: 1, category: "GNS211" },
  { q: "Which patient position is supine?", options: ["Lying on back", "Lying on stomach", "Sitting upright", "Side lying"], answer: 0, category: "GNS211" },
  { q: "Which patient position is prone?", options: ["Lying on back", "Lying on stomach", "Sitting upright", "Side lying"], answer: 1, category: "GNS211" },
  { q: "Which patient position is Fowler’s?", options: ["Lying flat", "Head elevated 45–60°", "Head down", "Side lying"], answer: 1, category: "GNS211" },
  { q: "Which is a normal pulse site?", options: ["Radial", "Carotid", "Brachial", "All of the above"], answer: 3, category: "GNS211" },

  // -------------------- GNS 210 – Anatomy (40) --------------------
  { q: "Largest organ in the human body?", options: ["Heart", "Liver", "Skin", "Lung"], answer: 2, category: "GNS210" },
  { q: "How many chambers does the heart have?", options: ["2", "3", "4", "5"], answer: 2, category: "GNS210" },
  { q: "Functional unit of the kidney?", options: ["Neuron", "Nephron", "Alveoli", "Osteon"], answer: 1, category: "GNS210" },
  { q: "The femur is located in?", options: ["Arm", "Leg", "Head", "Chest"], answer: 1, category: "GNS210" },
  { q: "Which system includes skin, hair, nails?", options: ["Nervous", "Integumentary", "Skeletal", "Muscular"], answer: 1, category: "GNS210" },
  { q: "Red blood cells are produced in?", options: ["Spleen", "Bone Marrow", "Liver", "Kidney"], answer: 1, category: "GNS210" },
  { q: "Where are the alveoli found?", options: ["Kidney", "Lung", "Heart", "Liver"], answer: 1, category: "GNS210" },
  { q: "Which organ produces insulin?", options: ["Pancreas", "Liver", "Kidney", "Spleen"], answer: 0, category: "GNS210" },
  { q: "The diaphragm separates?", options: ["Heart and lungs", "Thoracic and abdominal cavities", "Kidneys and bladder", "Brain and spinal cord"], answer: 1, category: "GNS210" },
  { q: "Largest part of the brain?", options: ["Cerebellum", "Medulla", "Cerebrum", "Pons"], answer: 2, category: "GNS210" },
  { q: "The trachea is part of which system?", options: ["Digestive", "Respiratory", "Circulatory", "Nervous"], answer: 1, category: "GNS210" },
  { q: "Which structure connects muscles to bones?", options: ["Ligaments", "Tendons", "Cartilage", "Fascia"], answer: 1, category: "GNS210" },
  { q: "The skin is part of?", options: ["Muscular system", "Integumentary system", "Circulatory system", "Skeletal system"], answer: 1, category: "GNS210" },
  { q: "Which blood cells fight infection?", options: ["Red", "White", "Platelets", "Plasma"], answer: 1, category: "GNS210" },
  { q: "The spinal cord passes through?", options: ["Skull", "Vertebrae", "Rib cage", "Pelvis"], answer: 1, category: "GNS210" },
  { q: "Which organ detoxifies chemicals?", options: ["Kidney", "Liver", "Lung", "Spleen"], answer: 1, category: "GNS210" },
  { q: "Which type of joint is the shoulder?", options: ["Hinge", "Ball and Socket", "Pivot", "Gliding"], answer: 1, category: "GNS210" },
  { q: "The cerebellum controls?", options: ["Breathing", "Balance and coordination", "Heart rate", "Vision"], answer: 1, category: "GNS210" },
  { q: "Which organ stores red blood cells?", options: ["Liver", "Spleen", "Kidney", "Pancreas"], answer: 1, category: "GNS210" },
  { q: "The alveoli function in?", options: ["Gas exchange", "Blood filtration", "Hormone secretion", "Immune response"], answer: 0, category: "GNS210" },
  { q: "Which organ produces bile?", options: ["Liver", "Pancreas", "Stomach", "Gallbladder"], answer: 0, category: "GNS210" },
  { q: "The axial skeleton includes?", options: ["Limbs", "Skull and vertebrae", "Pelvis", "Shoulder girdle"], answer: 1, category: "GNS210" },
  { q: "Ligaments connect?", options: ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Bone to organ"], answer: 0, category: "GNS210" },
  { q: "Tendons connect?", options: ["Bone to bone", "Muscle to bone", "Muscle to muscle", "Bone to organ"], answer: 1, category: "GNS210" },
  { q: "Which hormone regulates calcium in bones?", options: ["Insulin", "Parathyroid", "Adrenaline", "Thyroxine"], answer: 1, category: "GNS210" },
  { q: "The humerus is in?", options: ["Leg", "Arm", "Head", "Torso"], answer: 1, category: "GNS210" },
  { q: "Largest vein in the body?", options: ["Aorta", "Vena Cava", "Pulmonary vein", "Jugular vein"], answer: 1, category: "GNS210" },
  { q: "Smallest bones are found in?", options: ["Ear", "Hand", "Foot", "Skull"], answer: 0, category: "GNS210" },
  { q: "Which gland is the master gland?", options: ["Pituitary", "Thyroid", "Adrenal", "Pancreas"], answer: 0, category: "GNS210" },
  { q: "Which organ filters blood to produce urine?", options: ["Kidney", "Liver", "Heart", "Lung"], answer: 0, category: "GNS210" },
  { q: "What protects lungs from friction?", options: ["Pleura", "Pericardium", "Meninges", "Peritoneum"], answer: 0, category: "GNS210" },
  { q: "The cerebrum is responsible for?", options: ["Balance", "Thinking", "Breathing", "Heart rate"], answer: 1, category: "GNS210" },
  { q: "Which organ stores bile?", options: ["Liver", "Gallbladder", "Stomach", "Pancreas"], answer: 1, category: "GNS210" },
  { q: "Which organ is retroperitoneal?", options: ["Kidney", "Liver", "Heart", "Lung"], answer: 0, category: "GNS210" },
  { q: "Where is the thymus located?", options: ["Neck", "Between lungs", "Abdomen", "Pelvis"], answer: 1, category: "GNS210" },
  { q: "What is the functional unit of the respiratory system?", options: ["Alveoli", "Nephron", "Neuron", "Osteon"], answer: 0, category: "GNS210" },
  { q: "Which bone forms the forehead?", options: ["Frontal", "Parietal", "Occipital", "Temporal"], answer: 0, category: "GNS210" },
  { q: "Which bone forms the upper jaw?", options: ["Mandible", "Maxilla", "Zygomatic", "Nasal"], answer: 1, category: "GNS210" },
  { q: "The sternum protects?", options: ["Heart", "Lungs", "Both", "Brain"], answer: 2, category: "GNS210" },
  { q: "The patella is?", options: ["Knee cap", "Elbow bone", "Shoulder bone", "Ankle bone"], answer: 0, category: "GNS210" },
  { q: "The medulla oblongata controls?", options: ["Balance", "Heart rate", "Voluntary movement", "Vision"], answer: 1, category: "GNS210" },

  // -------------------- GNS 211 – Foundation (40) --------------------
  { q: "Which vital sign is considered the fifth vital sign?", options: ["Pain", "Pulse", "Respiration", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Normal adult blood pressure?", options: ["120/80 mmHg", "100/60 mmHg", "140/90 mmHg", "90/50 mmHg"], answer: 0, category: "GNS211" },
  { q: "Standard precautions prevent?", options: ["Patient comfort", "Infection spread", "Medication errors", "Diet errors"], answer: 1, category: "GNS211" },
  { q: "Hand hygiene reduces?", options: ["Pain", "Infection", "Stress", "Fatigue"], answer: 1, category: "GNS211" },
  { q: "Primary goal of nursing?", options: ["Diagnosis", "Patient care", "Research", "Administration"], answer: 1, category: "GNS211" },
  { q: "Which is a core nursing skill?", options: ["Suturing", "Medication administration", "Surgery", "Radiology"], answer: 1, category: "GNS211" },
  { q: "Normal adult pulse range?", options: ["40–60 bpm", "60–100 bpm", "100–120 bpm", "80–140 bpm"], answer: 1, category: "GNS211" },
  { q: "Fever is defined as?", options: [">37.5°C", ">38°C", ">39°C", ">36°C"], answer: 1, category: "GNS211" },
  { q: "Which oxygen saturation is normal?", options: ["<90%", "90–100%", "85–95%", "80–90%"], answer: 1, category: "GNS211" },
  { q: "Correct sequence of CPR?", options: ["CAB", "ABC", "BAC", "ACB"], answer: 0, category: "GNS211" },
  { q: "Normal adult respiration rate?", options: ["12–20/min", "20–30/min", "8–12/min", "10–18/min"], answer: 0, category: "GNS211" },
  { q: "Gloves are used for?", options: ["Protection", "Fashion", "Therapy", "Nutrition"], answer: 0, category: "GNS211" },
  { q: "Systolic pressure measures?", options: ["Heart relaxation", "Heart contraction", "Blood oxygen", "Pulse strength"], answer: 1, category: "GNS211" },
  { q: "Diastolic pressure measures?", options: ["Heart relaxation", "Heart contraction", "Pulse volume", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Which scale measures pain?", options: ["Glasgow", "Numeric", "APGAR", "Barthel"], answer: 1, category: "GNS211" },
  { q: "Which is part of patient safety?", options: ["Medication check", "Surgery alone", "Diagnosis only", "Lab work"], answer: 0, category: "GNS211" },
  { q: "Which is a nursing intervention?", options: ["Surgery", "Medication administration", "Diagnostic imaging", "Lab test"], answer: 1, category: "GNS211" },
  { q: "Standard precautions include?", options: ["Hand washing and PPE", "Diet planning", "Exercise", "Diagnostics"], answer: 0, category: "GNS211" },
  { q: "Which part of patient assessment?", options: ["Vital signs", "Lab result only", "Medication prescription", "Diet"], answer: 0, category: "GNS211" },
  { q: "Purpose of infection control?", options: ["Prevent spread", "Improve diet", "Administer drugs", "Surgery"], answer: 0, category: "GNS211" },
  { q: "Which part of hand hygiene is crucial?", options: ["Duration", "Brand", "Color", "Temperature"], answer: 0, category: "GNS211" },
  { q: "Which is a core nursing responsibility?", options: ["Patient care", "Diagnosis", "Surgery", "Lab test"], answer: 0, category: "GNS211" },
  { q: "Which body system monitors infection?", options: ["Immune system", "Digestive system", "Skeletal system", "Muscular system"], answer: 0, category: "GNS211" },
  { q: "Normal body temperature?", options: ["36–37°C", "35–36°C", "37–38°C", "38–39°C"], answer: 0, category: "GNS211" },
  { q: "Which protects against pathogens?", options: ["Gloves", "Sterile equipment", "Masks", "All of the above"], answer: 3, category: "GNS211" },
  { q: "Purpose of vital signs?", options: ["Diagnose disease", "Assess physiological status", "Prescribe drugs", "Treat illness"], answer: 1, category: "GNS211" },
  { q: "Primary reason for patient assessment?", options: ["Medication", "Baseline health info", "Surgery", "Exercise plan"], answer: 1, category: "GNS211" },
  { q: "Which patient position is supine?", options: ["Lying on back", "Lying on stomach", "Sitting upright", "Side lying"], answer: 0, category: "GNS211" },
  { q: "Which patient position is prone?", options: ["Lying on back", "Lying on stomach", "Sitting upright", "Side lying"], answer: 1, category: "GNS211" },
  { q: "Which patient position is Fowler’s?", options: ["Lying flat", "Head elevated 45–60°", "Head down", "Side lying"], answer: 1, category: "GNS211" },
  { q: "Which is a normal pulse site?", options: ["Radial", "Carotid", "Brachial", "All of the above"], answer: 3, category: "GNS211" },

  // -------------------- GNS 212 – Med-Surg (40) --------------------
  { q: "Which is a common symptom of infection?", options: ["Fever", "Bradycardia", "Hypotension", "Pallor"], answer: 0, category: "GNS212" },
  { q: "Which electrolyte is important for heart function?", options: ["Sodium", "Potassium", "Chloride", "Calcium"], answer: 1, category: "GNS212" },
  { q: "Preferred route for rapid medication?", options: ["Oral", "IV", "IM", "Subcutaneous"], answer: 1, category: "GNS212" },
  { q: "Normal fasting blood sugar?", options: ["70–100 mg/dL", "100–150 mg/dL", "150–200 mg/dL", "50–70 mg/dL"], answer: 0, category: "GNS212" },
  { q: "First sign of hypoxia?", options: ["Cyanosis", "Restlessness", "Bradycardia", "Hypotension"], answer: 1, category: "GNS212" },
  { q: "Which intervention prevents pressure ulcers?", options: ["Repositioning", "Medication", "Surgery", "Exercise"], answer: 0, category: "GNS212" },
  { q: "Normal respiratory rate for adults?", options: ["12–20", "8–12", "20–30", "10–15"], answer: 0, category: "GNS212" },
  { q: "Auscultation of lungs is done with?", options: ["Stethoscope", "Thermometer", "BP cuff", "Otoscope"], answer: 0, category: "GNS212" },
  { q: "Which diet for diabetes?", options: ["High sugar", "Low carb", "High fat", "Low protein"], answer: 1, category: "GNS212" },
  { q: "Best fluid replacement for dehydration?", options: ["Normal saline", "Dextrose 50%", "Lactated Ringer", "Albumin"], answer: 0, category: "GNS212" },
  { q: "Which organ is affected by hepatitis?", options: ["Liver", "Kidney", "Heart", "Lung"], answer: 0, category: "GNS212" },
  { q: "Which is a sign of hypoglycemia?", options: ["Sweating", "Dry skin", "Constipation", "Hypertension"], answer: 0, category: "GNS212" },
  { q: "Preferred site for intramuscular injection?", options: ["Deltoid", "Gluteus maximus", "Vastus lateralis", "All of the above"], answer: 3, category: "GNS212" },
  { q: "Which lab indicates kidney function?", options: ["Creatinine", "ALT", "AST", "Bilirubin"], answer: 0, category: "GNS212" },
  { q: "Which electrolyte imbalance causes arrhythmia?", options: ["Hypokalemia", "Hypercalcemia", "Hyponatremia", "Hypomagnesemia"], answer: 0, category: "GNS212" },
  { q: "Normal heart rate for adults?", options: ["60–100 bpm", "40–60 bpm", "100–120 bpm", "50–90 bpm"], answer: 0, category: "GNS212" },
  { q: "Which is a symptom of heart failure?", options: ["Dyspnea", "Constipation", "Diarrhea", "Fever"], answer: 0, category: "GNS212" },
  { q: "Which medication reduces pain?", options: ["Analgesic", "Antibiotic", "Antipyretic", "Diuretic"], answer:
